spring:
  kafka:
    properties:
      schema.registry.url: https://psrc-l622j.us-east-2.aws.confluent.cloud
      basic.auth.credentials.source: USER_INFO
      basic.auth.user.info:
  cloud:
    function:
      definition: user
    stream:
      kafka:
        binder:
          output-bindings: user-out-0
          brokers: pkc-12576z.us-west2.gcp.confluent.cloud:9092
          configuration:
            security.protocol: SASL_SSL
            sasl.mechanism: PLAIN
            sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='{{ CLUSTER_KEY}}' password='{{CLUSTER_SECRET}}';
            # Schema Registry settings
            # Avro serialization and deserialization configuration
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            # Auto register schema if not already registered
            auto.register.schemas: true
      bindings:
        user-in-0:
          destination: user-topic
          contentType: application/*+avro
          group: user-group
          consumer:
            useNativeDecoding: true
        user-out-0:
          destination: user-topic
          contentType: application/*+avro
          producer:
            useNativeEncoding: true

